/**
 * Decodificación de los PLC de transferencia eléctrica y textos de notificación.
 * Extraído de los nodos "Data Converter" de los flujos de Ramos Mejía y Castelar.
 *
 * - Ramos: lee 89 discrete inputs (FC2) desde 8000 (cada uno es un bit 0/1).
 * - Castelar: lee 3 holding registers desde 0 y los expande a bits (MSB primero).
 */
import { registersToBits } from '../acquisition/modbus/modbus.util';

export type SignalMap = Record<string, boolean>;

const on = (regs: number[], i: number): boolean => !!regs[i];

/** Ramos Mejía: cada índice corresponde a un discrete input FC2 (8000 + i). */
export function decodeRamos(regs: number[]): SignalMap {
  return {
    isTransferAut: on(regs, 1),
    isReturnAut: on(regs, 2),
    isTransferMan: !regs[1],
    isReturnMan: !regs[2],
    isUT2Ok: on(regs, 5),
    isCurrentAt45: on(regs, 6),
    isCurrentAt90: on(regs, 7),
    isG2Ready: on(regs, 8),
    isG3Ready: on(regs, 9),
    swT1Close: on(regs, 10),
    swT1Open: on(regs, 11),
    swT1Prot: on(regs, 12),
    swG1Close: on(regs, 13),
    swG1Open: on(regs, 14),
    swG1Prot: on(regs, 15),
    swT2Close: on(regs, 16),
    swT2Open: on(regs, 17),
    swT2Prot: on(regs, 18),
    swGsClose: on(regs, 19),
    swGsOpen: on(regs, 20),
    swGsProt: on(regs, 21),
    swHabT2Close: on(regs, 22),
    swHabT2Open: on(regs, 23),
    swHabT2Prot: on(regs, 24),
    swByPassClose: on(regs, 25),
    swByPassOpen: on(regs, 26),
    swByPassProt: on(regs, 27),
    isU1Fail: on(regs, 28),
    usU2Fail: on(regs, 29),
    usU3Fail: on(regs, 30),
    alarm02: on(regs, 32),
    alarm01: on(regs, 33),
    alarm03: on(regs, 34),
    alarm04: on(regs, 35),
    alarm05: on(regs, 36),
    alarm06: on(regs, 37),
    alarm07: on(regs, 38),
    alarm08: on(regs, 39),
    alarm09: on(regs, 40),
    alarm10: on(regs, 41),
    alarm11: on(regs, 42),
    alarm12: on(regs, 43),
    alarm13: on(regs, 44),
    alarm14: on(regs, 45),
    alarm15: on(regs, 46),
    alarm16: on(regs, 47),
    alarm17: on(regs, 48),
    alarm18: on(regs, 49),
    alarm18aux: !regs[49],
    alarm19: on(regs, 50),
    alarm20: on(regs, 51),
    alarm21: on(regs, 52),
    alarm22: on(regs, 53),
    alarm22aux: !regs[53],
    alarm23: on(regs, 54),
    alarm24: on(regs, 55),
    alarm25: on(regs, 56),
    alarm26: on(regs, 57),
    alarm27: on(regs, 58),
    alarm28: on(regs, 59),
    alarm29: on(regs, 60),
    alarm30: on(regs, 61),
    alarm31: on(regs, 62),
    alarm32: on(regs, 63),
    alarmU: on(regs, 64),
    alarmPlcEn: on(regs, 65),
    habT2ToG2: on(regs, 72),
    inhabT2ToG2: !regs[72],
    transferT2ToG2: on(regs, 73),
    stopT2ToG2: on(regs, 74),
    errorT2ToG2: on(regs, 75),
    habG2ToT2: on(regs, 76),
    inhabG2ToT2: !regs[76],
    transferG2ToT2: on(regs, 77),
    stopG2ToT2: on(regs, 78),
    errorG2ToT2: on(regs, 79),
    cmdSwT2Close: on(regs, 80),
    cmdSwT2Open: on(regs, 81),
    cmdGsClose: on(regs, 82),
    cmdGsOpen: on(regs, 83),
    cmdHabT2Close: on(regs, 84),
    cmdHabT2Open: on(regs, 85),
    cmdByPassClose: on(regs, 86),
    cmdByPassOpen: on(regs, 87),
    cmdGenRun: on(regs, 88),
  };
}

export const RAMOS_MESSAGES: Record<string, string> = {
  isTransferAut: 'Transferencia Automatica',
  isReturnAut: 'Retorno Automatico',
  isTransferMan: 'Transferencia Manual',
  isReturnMan: 'Retorno Manual',
  isUT2Ok: 'Tension en Transformador 2 OK',
  isCurrentAt45: 'Corriente maxima en 45%',
  isCurrentAt90: 'Corriente maxima en 90%',
  isG2Ready: 'G2 habilitado',
  isG3Ready: 'G3 habilitado',
  swT1Close: 'Interruptor Transformador 1 CERRADO',
  swT1Open: 'Interruptor Transformador 1 ABIERTO',
  swT1Prot: 'Interruptor Transformador 1 PROTECCION',
  swG1Close: 'Interruptor Generador 1 CERRADO',
  swG1Open: 'Interruptor Generador 1 ABIERTO',
  swG1Prot: 'Interruptor Generador 1 PROTECCION',
  swT2Close: 'Interruptor Transformador 2 CERRADO',
  swT2Open: 'Interruptor Transformador 2 ABIERTO',
  swT2Prot: 'Interruptor Transformador 2 PROTECCION',
  swGsClose: 'Interruptor Grupos CERRADO',
  swGsOpen: 'Interruptor Grupos ABIERTO',
  swGsProt: 'Interruptor Grupos PROTECCION',
  swHabT2Close: 'Interruptor Habilitacion T2 CERRADO',
  swHabT2Open: 'Interruptor habilitacion T2 ABIERTO',
  swHabT2Prot: 'Interruptor Habilitacion T2 PROTECCION',
  swByPassClose: 'Interruptor By-Pass CERRADO',
  swByPassOpen: 'Interruptor By-Pass ABIERTO',
  swByPassProt: 'Interruptor By-Pass PROTECCION',
  isU1Fail: 'Falla de tension barra 1',
  usU2Fail: 'Falla de tension barra 2',
  usU3Fail: 'Falla de tension barra 3',
  alarm02: 'Falta tension de comando en SET N1',
  alarm01: 'Falla en interruptor celda de entrada de SET N1',
  alarm03: 'Temperatura Trafo 1 previa',
  alarm04: 'Temperatura Trafo 1 disparo',
  alarm05: 'Fusible MT Trafo 1 actuado',
  alarm06: 'Sobreintensidad Interruptor BT 1',
  alarm07: 'Cortocircuito Interruptor BT 1',
  alarm08: 'Falta tension de comando en SET N2',
  alarm09: 'Temperatura Trafo 2 previa',
  alarm10: 'Temperatura Trafo 2 disparo',
  alarm11: 'Fusible MT Trafo 2 actuado',
  alarm12: 'Sobreintensidad Interruptor G1 (Reserva)',
  alarm13: 'Cortocircuito Interruptor G1 (Reserva)',
  alarm14: 'Resumidor de Grupo Electrogeno G1 (Reserva)',
  alarm15: 'Sobreintensidad Interruptor G2',
  alarm16: 'Cortocircuito Interruptor G2',
  alarm17: 'Resumidor de Grupo Electrogeno G2',
  alarm18: 'Interruptor Grupo electrogeno G2 cerrado',
  alarm18aux: 'Interruptor Grupo electrogeno G2 abierto',
  alarm19: 'Sobreintensidad Interruptor G3',
  alarm20: 'Cortocircuito Interruptor G3',
  alarm21: 'Resumidor de Grupo Electrogeno G3',
  alarm22: 'Interruptor Grupo electrogeno G3 cerrado',
  alarm22aux: 'Interruptor Grupo electrogeno G3 abierto',
  alarm23: 'Falla paraleling Grupos electrogenos',
  alarm24: 'Sobretemperatura en Equipo corrector cos.fi',
  alarm25: 'Generador 2 en Manual',
  alarm26: 'Generador 3 en Manual',
  alarm27: 'Falla PLC Enclavamientos',
  alarm28: 'Falla PLC Automatismo',
  alarm29: 'Transferencia NO Habilitada',
  alarm30: 'Retorno NO Habilitado',
  alarm31: 'Falla Transferencia',
  alarm32: 'Alarma desconocida',
  alarmU: 'Falla reles de Minima',
  alarmPlcEn: 'Falla PLC Enclavamientos',
  habT2ToG2: 'T2 a G2 habilitado',
  inhabT2ToG2: 'T2 a G2 no habilitado',
  transferT2ToG2: 'Transfieriendo de T2 a G2',
  stopT2ToG2: 'Transferencia de T2 a G2 detenida',
  errorT2ToG2: 'Error en transferencia de T2 a G2',
  habG2ToT2: 'G2 a T2 habilitado',
  inhabG2ToT2: 'G2 a T2 no habilitado',
  transferG2ToT2: 'Transfiriendo de G2 a T2',
  stopG2ToT2: 'Transferencia de G2 a T2 detenida',
  errorG2ToT2: 'Error en transferencia de G2 a T2',
  cmdSwT2Close: 'Comando de cierre interruptor T2',
  cmdSwT2Open: 'Comando de apertura interruptor T2',
  cmdGsClose: 'Comando de cierre interruptor grupos',
  cmdGsOpen: 'Comando de apertura interruptor grupos',
  cmdHabT2Close: 'Comando de cierre interruptor habilitacion T2',
  cmdHabT2Open: 'Comando de apertura interruptor habilitacion T2',
  cmdByPassClose: 'Comando de cierre By-Pass',
  cmdByPassOpen: 'Comando de apertura By-Pass',
  cmdGenRun: 'Comando de arranque generadores',
};

/** Castelar: expande 3 holding registers a 48 bits (MSB primero). */
export function decodeCastelar(regs: number[]): SignalMap {
  const bits = registersToBits(regs);
  const b = (i: number): boolean => !!bits[i];
  return {
    W2: b(0),
    W1: b(1),
    DESTR1: b(2),
    TTR1: b(3),
    SDE_MT: b(4),
    MT: b(5),
    INCENDIO: b(6),
    AUT: b(7),
    SDE_Q4: b(8),
    Q4: b(9),
    Q4AUX: !bits[9],
    SDE_Q3: b(10),
    Q3: b(11),
    Q3AUX: !bits[11],
    SDE_Q2: b(12),
    Q2: b(13),
    Q2AUX: !bits[13],
    SDE_Q1: b(14),
    Q1: b(15),
    Q1AUX: !bits[15],
    NO_HAY_UG: b(16),
    MAN: b(17),
    C_GE2: b(18),
    AUT_GE2: b(19),
    MAN_GE2: !bits[19],
    ALR_GE2: b(20),
    INT_GE2: b(21),
    INT_GE2AUX: !bits[21],
    C_GE1: b(22),
    AUT_GE1: b(23),
    MAN_GE1: !bits[23],
    ALR_GE1: b(24),
    INT_GE1: b(25),
    INT_GE1AUX: !bits[25],
    RES1: b(26),
    UGE2: b(27),
    UGE1: b(28),
    UCIA: b(29),
    NO_UCIA: !bits[29],
    W4: b(30),
    W3: b(31),
    TGBT_CON_GE: b(47),
  };
}

export const CASTELAR_MESSAGES: Record<string, string> = {
  W2: 'Alimentacion de comando desde trafo',
  W1: 'Alimentacion de comando desde UPS',
  DESTR1: 'Apertura de celda por temperatura',
  TTR1: 'Alta temperatura en transformador',
  SDE_MT: 'Sobre intensidad en celda de media tension',
  MT: 'Celda de media tension abierta',
  INCENDIO: 'Señal de incendio',
  AUT: 'Retorno en automatico',
  SDE_Q4: 'Falla interruptor de GE 2',
  Q4: 'Interuptor de GE 2 cerrado (en TGBT)',
  Q4AUX: 'Interuptor de GE 2 abierto (en TGBT)',
  SDE_Q3: 'Falla interruptor de enlace',
  Q3: 'Interuptor de enlace cerrado',
  Q3AUX: 'Interuptor de enlace abierto',
  SDE_Q2: 'Falla interruptor de GE 1',
  Q2: 'Interuptor de GE 1 cerrado (en TGBT)',
  Q2AUX: 'Interuptor de GE 1 abierto (en TGBT)',
  SDE_Q1: 'Falla interruptor de compania',
  Q1: 'Interuptor de compania cerrado',
  Q1AUX: 'Interuptor de compania abierto',
  NO_HAY_UG: 'No hay tension de grupos',
  MAN: 'Retorno en manual',
  C_GE2: 'Orden de cierre interruptor GE 2 en TGBT',
  AUT_GE2: 'GE 2 en automatico',
  MAN_GE2: 'GE 2 en manual',
  ALR_GE2: 'Alarma en GE 2',
  INT_GE2: 'Interruptor en GE 2 cerrado',
  INT_GE2AUX: 'Interruptor en GE 2 abierto',
  C_GE1: 'Orden de cierre interruptor GE 1 en TGBT',
  AUT_GE1: 'GE 1 en automatico',
  MAN_GE1: 'GE 1 en manual',
  ALR_GE1: 'Alarma en GE 1',
  INT_GE1: 'Interruptor en GE 1 cerrado',
  INT_GE1AUX: 'Interruptor en GE 1 abierto',
  RES1: '',
  UGE2: 'Tension en GE 2',
  UGE1: 'Tension en GE 1',
  UCIA: 'Tension de compania',
  NO_UCIA: 'Sin tension de compania',
  W4: 'Alimentacion de comando desde GE 2',
  W3: 'Alimentacion de comando desde GE 1',
  TGBT_CON_GE: 'Tablero TGBT con tension de grupos',
};
